src/backend/controllers/FileController.php
<?php

namespace backend\controllers;

use api\forms\file\PhotosForm;
use lib\services\file\FileService;
use Yii;
use yii\web\Controller;
use yii\web\Response;

/**
 * NewsController implements the CRUD actions for News model.
 */
class FileController extends Controller
{
    public function verbs(): array
    {
        return [
            'image-upload' => ['POST'],
            'get'    => ['GET'],
        ];
    }


    /**
     * @throws \api\exceptions\Http400Exception
     */
    public function actionImageUpload()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        $form = new PhotosForm();
        $form->load(\Yii::$app->request->post(), '');
        $form->validate();

        $file = FileService::saveOrReturnExistFile($form->file);
        $url = FileService::getUrl($file);

        return [
            [
                'thumb' => $url,
                'url'   => $url,
                'id'    => $file->id,
                'title' => $file->name,
            ]
        ];

    }


    /**
     * @param $hash
     *
     * @throws Http400Exception
     * @throws ServerErrorHttpException
     */
    public function actionGet($hash)
    {
        if ( ! $file = FileService::checkIfFileExistByHash($hash))
            throw new Http400Exception('File not found');

        $response = \Yii::$app->getResponse();
        $response->headers->set('Content-Type', 'image/jpeg');
        $response->format = \yii\web\Response::FORMAT_RAW;
        if ( ! is_resource($response->stream = fopen($file->path, 'r')))
        {
            throw new ServerErrorHttpException('file access failed: permission deny');
        }

        return $response->send();
    }
}

src/backend/controllers/NewsController.php
<?php

namespace backend\controllers;

use api\forms\news\NewsForm;
use common\base\Assert;
use common\entities\news\NewsSearch;
use Yii;
use common\entities\news\News;
use common\entities\news\EventSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * NewsController implements the CRUD actions for News model.
 */
class NewsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all News models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new NewsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single News model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new News model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $form = new NewsForm();

        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            dd($form);
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $form,
        ]);
    }

    /**
     * Updates an existing News model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing News model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the News model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return News the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = News::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }


    public function actionModerate($id)
    {
        $item = News::findById($id);
        Assert::notFound($item);
        
        if(Yii::$app->request->isPost){
            $action = Yii::$app->request->get('action');
            
            if($action == 'reject'){
                $item->setReject();
            }
            
            if($action == 'public'){
                $item->setPublic();
            }
    
            return $this->redirect(['index']);
            
        }

        return $this->render('moderate', [
            'model' => $item,
        ]);
    }
}

src/backend/views/news/_form.php
<?php

use kartik\widgets\DateTimePicker;
use kartik\widgets\FileInput;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\entities\news\News */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="news-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'description_short')->widget(\vova07\imperavi\Widget::class, [
        'settings' => [
            'lang'      => 'ru',
            'minHeight' => 200,
            'plugins'   => [
            ],
        ],
    ]) ?>

    <?= $form->field($model, 'description')->widget(\vova07\imperavi\Widget::class, [
        'settings' => [
            'lang'        => 'ru',
            'minHeight'   => 200,
            'imageUpload' => Url::to(['/file/image-upload']),
            'plugins'     => [
                'imagemanager',
            ],

        ],
    ]) ?>


    <?= $form->field($model, 'team_id')->widget(\kartik\select2\Select2::class, [
        'data'    => \common\entities\team\Team::map('id', 'title'),
        'options' => ['placeholder' => Yii::t('app', 'Select team')]
    ]) ?>


    <?= $form->field($model, 'country_id')->widget(\kartik\select2\Select2::class, [
        'data'    => \common\entities\geo\Countries::map('country_id', 'title_ru'),
        'options' => ['placeholder' => Yii::t('app', 'Select country')]
    ]) ?>

    <?= $form->field($model, 'region_id')->widget(\kartik\select2\Select2::class, [
        'data'    => \common\entities\geo\Regions::map('region_id', 'title_ru'),
        'options' => ['placeholder' => Yii::t('app', 'Select region')]
    ]) ?>

    <?= $form->field($model, 'city_id')->widget(\kartik\select2\Select2::class, [
        'data'    => \common\entities\geo\Cities::map('city_id', 'title_ru'),
        'options' => ['placeholder' => Yii::t('app', 'Select city')]
    ]) ?>


    <?= $form->field($model, 'photo_id')->widget(FileInput::class, [
        'name'          => 'file[]',
        'options'       => [
            'accept' => 'image/*',
        ],
        'pluginOptions' => [
            'uploadUrl'    => Url::to(['/file/image-upload']),
            'maxFileCount' => 1
        ]
    ]) ?>

    <?= $form->field($model, 'type')->widget(\kartik\select2\Select2::class, [
        'data'    => \common\dictionaries\NewsType::all(),
        'options' => ['placeholder' => Yii::t('app', 'Select type')]
    ]) ?>

    <?= $form->field($model, 'post_date')->widget(\kartik\datetime\DateTimePicker::class, [
        'options'       => ['placeholder' => Yii::t('app', 'Select time')],
        'pluginOptions' => [
            'autoclose' => true,
            'format'    => 'yyyy-mm-dd hh:ii:ss',
            'todayBtn'  => true
        ]
    ]) ?>


    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

src/backend/views/news/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\entities\news\EventSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="news-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'owner_id') ?>

    <?= $form->field($model, 'team_id') ?>

    <?= $form->field($model, 'country_id') ?>

    <?php // echo $form->field($model, 'city_id') ?>

    <?php // echo $form->field($model, 'region_id') ?>

    <?php // echo $form->field($model, 'description_short') ?>

    <?php // echo $form->field($model, 'description') ?>

    <?php // echo $form->field($model, 'photo_id') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'type') ?>

    <?php // echo $form->field($model, 'post_date') ?>

    <?php // echo $form->field($model, 'views') ?>

    <?php // echo $form->field($model, 'likes') ?>

    <?php // echo $form->field($model, 'shares') ?>

    <?php // echo $form->field($model, 'stars') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

src/backend/views/news/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\entities\news\News */

$this->title = Yii::t('app', 'Create News');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'News'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="news-create">

<!--    <h1>--><?//= Html::encode($this->title) ?><!--</h1>-->

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

src/backend/views/news/index.php
<?php

use kartik\widgets\DatePicker;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\entities\news\EventSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'News');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="news-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('app', 'Create News'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel'  => $searchModel,
        'columns'      => [
            ['class' => 'yii\grid\SerialColumn'],
            
            //            'id',
            'title',
            'owner.phone',
            //            'team_id',
            //            'country_id',
            //            'city_id',
            //'region_id',
            //'description_short',
            'description:ntext',
            //'photo_id',
            [
                'attribute' => 'status',
                'filter'    => $searchModel->statusList(),
                'value'     => function(\common\entities\news\News $model){
                    return \common\dictionaries\NewsStatus::label($model->status);
                },
                'format'    => 'raw',
            ],
            [
                'attribute' => 'type',
                'filter'    => $searchModel->typeList(),
                'value'     => function(\common\entities\news\News $model){
                    return \common\dictionaries\NewsType::label($model->type);
                },
                'format'    => 'raw',
            ],
            //            [
            //                'attribute' => 'post_date',
            //                'filter' => DatePicker::widget([
            //                    'model' => $searchModel,
            //                    'attribute' => 'post_date_from',
            //                    'attribute2' => 'post_date_to',
            //                    'type' => DatePicker::TYPE_RANGE,
            //                    'separator' => '-',
            //                    'pluginOptions' => [
            //                        'todayHighlight' => true,
            //                        'autoclose'=>true,
            //                        'format' => 'yyyy-mm-dd',
            //                    ],
            //                ]),
            //                'format' => 'datetime',
            //            ],
            ['attribute' => 'post_date', 'format' => ['date', 'Y-M-d H:i:s'],],
            ['attribute' => 'post_date_close', 'format' => ['date', 'Y-M-d H:i:s'],],
            //'views',
            //'likes',
            //'shares',
            [
                'attribute' => 'created_at',
                'format'    => ['date', 'Y-M-d H:i:s'],
            ],
            //'updated_at',
            
            [
                'class'    => 'yii\grid\ActionColumn',
                'template' => '{view} {moderate} {delete}',
                'buttons'  => [
                    'moderate' => function($url, $model, $key){
                        if($model->canModerate()){
                            return Html::a('moderate', ['moderate', 'id' => $model->id]);
                        }
                        return null;
                    }
                ]
            ],
        ],
    ]); ?>
</div>

src/backend/views/news/moderate.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\entities\news\News */

$this->title = Yii::t('app', 'Moderate News: ' . $model->title, [
    'nameAttribute' => '' . $model->title,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'News'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Moderate');
?>
<div class="news-moderate">


    <?= DetailView::widget([
        'model'      => $model,
        'attributes' => [
            'id',
            'title',
            'description:ntext',
            [
                'attribute' => 'photo_id',
                'value'     => function(\common\entities\news\News $model){
                    return Html::img(\lib\services\file\FileService::getUrl($model->photo));
                },
                'format'    => 'raw',
            ],
            [
                'attribute' => 'status',
                'value'     => function(\common\entities\news\News $model){
                    return \common\dictionaries\NewsStatus::label($model->status);
                },
                'format'    => 'raw',
            ],
            [
                'attribute' => 'type',
                'value'     => function(\common\entities\news\News $model){
                    return \common\dictionaries\NewsType::label($model->type);
                },
                'format'    => 'raw',
            ],
            'post_date',
            'created_at',
        ],
    ]) ?>

    <?php if ($model->canModerate()): ?>
        <?= Html::a('Reject', ['moderate', 'id' => $model->id, 'action' => 'reject'], ['class' => 'btn btn-danger', 'data-method' => 'post', 'data-confirm' => 'Уверены?']) ?>
        <?= Html::a('Public', ['moderate', 'id' => $model->id, 'action' => 'public'], ['class' => 'btn btn-success', 'data-method' => 'post', 'data-confirm' => 'Уверены?']) ?>
    <?php endif; ?>
    
    
    

</div>

src/backend/views/news/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\entities\news\News */

$this->title = Yii::t('app', 'Update News: ' . $model->title, [
    'nameAttribute' => '' . $model->title,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'News'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="news-update">

<!--    <h1>--><?//= Html::encode($this->title) ?><!--</h1>-->

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

src/backend/views/news/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\entities\news\News */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'News'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="news-view">

<!--    <h1>--><?//= Html::encode($this->title) ?><!--</h1>-->

    <p>
<!--        --><?//= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?php if($model->canModerate()){ ?>
            <?= Html::a(Yii::t('app', 'Moderate'), ['moderate', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?php } ?>


<!--        --><?//= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
//            'class' => 'btn btn-danger',
//            'data'  => [
//                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
//                'method'  => 'post',
//            ],
//        ]) ?>
    </p>

    <?= DetailView::widget([
        'model'      => $model,
        'attributes' => [
            'id',
            'title',
            'owner.phone',
            'team_id',
            'country.title_ru',
            'city.title_ru',
            'region.title_ru',
            'description:ntext',
            [
                'attribute' => 'photo_id',
                'value'     => function(\common\entities\news\News $model){
                    return Html::img(\lib\services\file\FileService::getUrl($model->photo));
                },
                'format'    => 'raw',
            ],
            [
                'attribute' => 'status',
                'value'     => function(\common\entities\news\News $model){
                    return \common\dictionaries\NewsStatus::label($model->status);
                },
                'format'    => 'raw',
            ],
            [
                'attribute' => 'type',
                'value'     => function(\common\entities\news\News $model){
                    return \common\dictionaries\NewsType::label($model->type);
                },
                'format'    => 'raw',
            ],
            'post_date',
            'views',
            'likes',
            'shares',
            'created_at',
            'updated_at',
        ],
    ]) ?>

</div>